language: node_js
dist: trusty
node_js:
  - 9
  - 8
  - 7
notifications:
  email:
    on_failure: change
script:
  - node --version
  - yarn --version
  - yarn run lint
  - yarn run test:noWatch
  - ls ./coverage
  - codecov
  - yarn run build
cache:
  yarn: true
  directories:
    - node_modules