language: node_js
dist: trusty
node_js:
  - 9
  - 8
  - 7
notifications:
  email:
    on_failure: change
script:
  - node --version
  - yarn --version
  - yarn run securityCheck
  - yarn run lint
  - yarn run test:noWatch
  - codecov
  - yarn run build
cache:
  yarn: true
  directories:
    - node_modules
before_install: 
  - yarn global add greenkeeper-lockfile@1
before_script: 
  - greenkeeper-lockfile-update
  - echo "Ran 'greenkeeper-lockfile-update'""
after_script: 
  - greenkeeper-lockfile-upload 
  - echo "Ran 'greenkeeper-lockfile upload'"